name: Go CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
          
      - name: Verify Go Installation
        run: go version

      - name: Install Dependencies
        run: go mod tidy

      - name: Run Unit Tests
        run: go test ./...

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t devisri2104/task-manager .

      - name: Push Docker Image
        run: docker push devisri2104/task-manager
