name: Go CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15  # Use a stable PostgreSQL version
        env:
          POSTGRES_USER: runner
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U runner"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Verify Go Installation
        run: go version

      - name: Install Dependencies
        run: go mod tidy

      - name: Wait for PostgreSQL
        run: sleep 10  # Wait for PostgreSQL to start

      - name: Run Unit Tests
        env:
          DATABASE_URL: postgres://runner:password@localhost:5432/testdb?sslmode=disable
        run: go test ./...

  docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t devisri2104/task-manager .

      - name: Push Docker Image
        run: docker push devisri2104/task-manager

